apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres-mcp
  namespace: devpool
spec:
  project: default
  source:
    repoURL: git@github.com:Tecurious/Tecurious-Infra.git
    targetRevision: feature/organise
    path: infrastructure/apps/postgres-mcp
  destination:
    server: https://kubernetes.default.svc
    namespace: data
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
