apiVersion: v1
kind: Service
metadata:
  namespace: dev
  name: 9router
  labels:
    app: 9router
spec:
  type: NodePort
  selector:
    app: 9router
  ports:
    - name: http
      port: 20128
      targetPort: 20128
      nodePort: 30320
